Проверка факта, что все правильные семейства из линейных функции - треугольные с точностью до перестановки

In [1]:
import itertools as it
import numpy as np
import copy
from tqdm import tqdm

Генерируем наборы значений переменных x,y,z

In [2]:
args = np.array(tuple(it.product((0,1,2), repeat = 3)))
args

array([[0, 0, 0],
       [0, 0, 1],
       [0, 0, 2],
       [0, 1, 0],
       [0, 1, 1],
       [0, 1, 2],
       [0, 2, 0],
       [0, 2, 1],
       [0, 2, 2],
       [1, 0, 0],
       [1, 0, 1],
       [1, 0, 2],
       [1, 1, 0],
       [1, 1, 1],
       [1, 1, 2],
       [1, 2, 0],
       [1, 2, 1],
       [1, 2, 2],
       [2, 0, 0],
       [2, 0, 1],
       [2, 0, 2],
       [2, 1, 0],
       [2, 1, 1],
       [2, 1, 2],
       [2, 2, 0],
       [2, 2, 1],
       [2, 2, 2]])

Делаем то же самое, но вместе с номером набора

In [3]:
num_args = tuple(enumerate(it.product((0,1,2), repeat = 3)))
num_args

((0, (0, 0, 0)),
 (1, (0, 0, 1)),
 (2, (0, 0, 2)),
 (3, (0, 1, 0)),
 (4, (0, 1, 1)),
 (5, (0, 1, 2)),
 (6, (0, 2, 0)),
 (7, (0, 2, 1)),
 (8, (0, 2, 2)),
 (9, (1, 0, 0)),
 (10, (1, 0, 1)),
 (11, (1, 0, 2)),
 (12, (1, 1, 0)),
 (13, (1, 1, 1)),
 (14, (1, 1, 2)),
 (15, (1, 2, 0)),
 (16, (1, 2, 1)),
 (17, (1, 2, 2)),
 (18, (2, 0, 0)),
 (19, (2, 0, 1)),
 (20, (2, 0, 2)),
 (21, (2, 1, 0)),
 (22, (2, 1, 1)),
 (23, (2, 1, 2)),
 (24, (2, 2, 0)),
 (25, (2, 2, 1)),
 (26, (2, 2, 2)))

Генерируем всевозможные пары различных нумерованных наборов значений трёх переменных

In [4]:
pairs = tuple(it.combinations(num_args, 2))
pairs

(((0, (0, 0, 0)), (1, (0, 0, 1))),
 ((0, (0, 0, 0)), (2, (0, 0, 2))),
 ((0, (0, 0, 0)), (3, (0, 1, 0))),
 ((0, (0, 0, 0)), (4, (0, 1, 1))),
 ((0, (0, 0, 0)), (5, (0, 1, 2))),
 ((0, (0, 0, 0)), (6, (0, 2, 0))),
 ((0, (0, 0, 0)), (7, (0, 2, 1))),
 ((0, (0, 0, 0)), (8, (0, 2, 2))),
 ((0, (0, 0, 0)), (9, (1, 0, 0))),
 ((0, (0, 0, 0)), (10, (1, 0, 1))),
 ((0, (0, 0, 0)), (11, (1, 0, 2))),
 ((0, (0, 0, 0)), (12, (1, 1, 0))),
 ((0, (0, 0, 0)), (13, (1, 1, 1))),
 ((0, (0, 0, 0)), (14, (1, 1, 2))),
 ((0, (0, 0, 0)), (15, (1, 2, 0))),
 ((0, (0, 0, 0)), (16, (1, 2, 1))),
 ((0, (0, 0, 0)), (17, (1, 2, 2))),
 ((0, (0, 0, 0)), (18, (2, 0, 0))),
 ((0, (0, 0, 0)), (19, (2, 0, 1))),
 ((0, (0, 0, 0)), (20, (2, 0, 2))),
 ((0, (0, 0, 0)), (21, (2, 1, 0))),
 ((0, (0, 0, 0)), (22, (2, 1, 1))),
 ((0, (0, 0, 0)), (23, (2, 1, 2))),
 ((0, (0, 0, 0)), (24, (2, 2, 0))),
 ((0, (0, 0, 0)), (25, (2, 2, 1))),
 ((0, (0, 0, 0)), (26, (2, 2, 2))),
 ((1, (0, 0, 1)), (2, (0, 0, 2))),
 ((1, (0, 0, 1)), (3, (0, 1, 0))),
 ((

Функция, возвращающая индексы позиций, в которых отличаются два вектора

In [5]:
def diff_idx(x,y):
    return (i for (i,(a,b)) in enumerate(zip(x,y)) if a!=b)

Функция выдаёт список значений линейной функции на всевозможных наборах аргументов

In [6]:
def func_values(coef):
    return np.fromiter((lin_func(coef, arg) for arg in args), dtype=int)

Функция вычисляет значение линейной функции в точке arg c коэффициентами coef

In [7]:
def lin_func(coef, arg):
    return np.sum(coef*np.append(1,arg))%3

Проверка семейства на правильность по определению

In [8]:
def check(fam):
    fam = np.array(list(map(func_values,fam)))
    for p in pairs:
        flag = False
        for idx in diff_idx(p[0][1],p[1][1]):
            if fam[idx][p[0][0]] == fam[idx][p[1][0]]:
                flag = True
                break
        if not flag:
            break
    return flag

Генерация всевозможных линейных функций с помощью коэффициентов (по порядку: 1, x, y, z)

In [9]:
coef = np.array(tuple(it.product((0,1,2), repeat = 4)))

f_0 - итератор, содержащий все линейные функции не зависящие от x, f_1 - от y, f_2 - от z. В переменной iterator содержится декартово произведение f_0 x f_1 x f_2, то есть семейства-кандидаты на правильность

In [10]:
f_0 = coef[coef[:,1]==0]
f_1 = coef[coef[:,2]==0]
f_2 = coef[coef[:,3]==0]
iterator = it.product(f_0, f_1, f_2)

Подсчёт правильных семейств линейных функций (переменная s). Правильные семейства хранятся в переменной lst

In [11]:
s = 0
lst = []
for _ in tqdm(range(19683)):
    elem = np.array(next(iterator))
    if check(elem):
        s += 1
        lst.append(elem)
print(s, s/19683)

100%|██████████| 19683/19683 [00:09<00:00, 2060.95it/s]

2943 0.149519890260631


Конвератция в numpy-массив для удобной работы в дальнейшем

In [12]:
lst = np.array(lst)
lst

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 1, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 2, 0]],

       ...,

       [[2, 0, 2, 2],
        [2, 0, 0, 2],
        [0, 0, 0, 0]],

       [[2, 0, 2, 2],
        [2, 0, 0, 2],
        [1, 0, 0, 0]],

       [[2, 0, 2, 2],
        [2, 0, 0, 2],
        [2, 0, 0, 0]]])

Проверка семейства на треугольность

In [13]:
def trg(fam):
    if np.all(fam[0][1:] == 0) and np.all(fam[1][2:] == 0) and np.all(fam[2][3:] == 0):
        return True
    else: 
        return False

Генерация семейства, полученного из входного семейства fam путём применения перестановки perm на функциях семейства и их аргументах. Перестановка на аргументах осуществляется перестановкой коэффициентов многочлена в нужном порядке

In [14]:
def fam_perm(fam, perm):
    c = copy.deepcopy(fam)
    for i in range(len(c)):
        c[i][1:] = c[i][1:][perm]
    return c[perm]    

Всевозможные перестановки из 3 элементов

In [15]:
perm = np.array(tuple(it.permutations(range(3))))
perm

array([[0, 1, 2],
       [0, 2, 1],
       [1, 0, 2],
       [1, 2, 0],
       [2, 0, 1],
       [2, 1, 0]])

Проверка семейства на треугольность посредством проверки на треугольность всевозможных семейств, полученных из входного fam c помощью всевозможных перестановок на функциях семейства и их аргументах

In [16]:
def check_trg(fam):
    flag = False
    for p in perm:
        if trg(fam_perm(fam, p)):
            flag = True
            break
    return flag

Проверка того, что все правильные семейства (переменная lst) являются треугольными

In [17]:
count = 0
for fam in lst:
    if check_trg(fam):
        count += 1
    else:
        print(fam)
print(count)

2943
