Среди полученных правильных семейств порядка 3 осуществляется поиск треугольных и ортогональных семейств и семейств, которые не вошли ни в один из этих 2 классов. Также ищутся пересечения этих классов.

In [1]:
import numpy as np
import itertools as it
from ipynb.fs.full.functions_for_clf import check_ort, check_trg_aft_perm, check_const
import multiprocessing
from math import ceil

Выгружаем numpy-массив, состоящий из всех правильных семейств порядка 3

In [2]:
data = np.load('all_fams_2.npz')['arr_0']

In [3]:
data.shape

(744, 3, 8)

Количество семейств, содержащих хотя бы одну константу

In [4]:
check_const_res = np.fromiter(map(check_const, data), dtype=bool)
const_fams_2 = data[check_const_res]
const_fams_2.shape

(680, 3, 8)

In [6]:
for fam in const_fams_2:
    print(fam)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 1 1]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 1 1 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 1 1 0 0 1 1]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 1 1 1 1 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 1 1 1 1 1 1]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 1 1]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [1 1 0 0 1 1 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [1 1 0 0 1 1 1 1]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [1 1 1 1 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [1 1 1 1 0 0 1 1]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 1]
 [0 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 

In [8]:
ort_res = np.fromiter(map(check_ort, data), dtype=bool)
trg_res = np.fromiter(map(check_trg_aft_perm, data), dtype=bool)
ort_trg_res = ort_res & trg_res
other_res = ~(ort_res | trg_res)
ort_fams_2 = data[ort_res]
trg_fams_2 = data[trg_res]
ort_trg_fams_2 = data[ort_trg_res]
other_fams_2 = data[other_res]
np.savez_compressed('ort_fams_2', ort_fams_2)
np.savez_compressed('trg_fams_2', trg_fams_2)
np.savez_compressed('ort_trg_fams_2', ort_trg_fams_2)
np.savez_compressed('other_fams_2', other_fams_2)

In [10]:
ort_fams_2.shape[0], ort_fams_2.shape[0]/data.shape[0]

(108, 0.14516129032258066)

In [11]:
trg_fams_2.shape[0], trg_fams_2.shape[0]/data.shape[0]

(392, 0.5268817204301075)

In [12]:
ort_trg_fams_2.shape[0], ort_trg_fams_2.shape[0]/data.shape[0]

(68, 0.0913978494623656)

In [13]:
other_fams_2.shape[0], other_fams_2.shape[0]/data.shape[0]

(312, 0.41935483870967744)